In [2]:
from sklearn import preprocessing
import numpy as np

In [5]:
X = np.array([[1, 0, -1], [2, 1, 0], [-1, -1, 2]])
X

array([[ 1,  0, -1],
       [ 2,  1,  0],
       [-1, -1,  2]])

In [8]:
preprocessing.scale(X)

array([[ 0.26726124,  0.        , -1.06904497],
       [ 1.06904497,  1.22474487, -0.26726124],
       [-1.33630621, -1.22474487,  1.33630621]])

In [6]:
scaler = preprocessing.StandardScaler()
scaler.fit(X)

scaler.transform(X)

array([[ 0.26726124,  0.        , -1.06904497],
       [ 1.06904497,  1.22474487, -0.26726124],
       [-1.33630621, -1.22474487,  1.33630621]])

In [9]:
scaler.transform([[1, 2, 2]])

array([[0.26726124, 2.44948974, 1.33630621]])